AutoMarket/Models/Enums/MotorcycleType.cs
namespace Models.Enums
{
    public enum MotorcycleType
    {
        DirtBike,
        Quad,
        Scooter,
        Racing,
        Tourer,
        Other
    }
}

AutoMarket/Models/Motorcycle.cs
using Microsoft.AspNetCore.Identity;
using Models.Enums;

namespace AutoMarket.Models
{
    public class Motorcycle
    {
        public int Id { get; set; }
        public DateTime FirstRegistration { get; set; }
        public int EnginePower { get; set; }
        public float Price { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public MotorcycleType MotorcycleType { get; set; }
        public Condition Condition { get; set; }
        public Color Color { get; set; }
        public FuelType FuelType { get; set; }
        public Mileage Mileage { get; set; }
        public TransmissionType TransmissionType { get; set; }
        public int MotorcycleBrandId { get; set; }
        public int MotorcycleModelId { get; set; }
        public MotorcycleBrand? MotorcycleBrand { get; set; }
        public MotorcycleModel? MotorcycleModel { get; set; }
        public IdentityUser? User { get; set; }
        public List<MotorcyclePhoto>? Photos { get; set; }

    }
}

AutoMarket/Controllers/MotorcyclesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoMarket.Data;
using AutoMarket.Models;
using X.PagedList;
using Microsoft.AspNetCore.Identity;
using AutoMarket.ViewModel;
using Models.Enums;

namespace AutoMarket.Controllers
{
    public class MotorcyclesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public MotorcyclesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: Cars
        public async Task<IActionResult> Index(int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 4;

            var motorcycle = await _context.Motorcycles
                .Include(c => c.MotorcycleBrand)
                .Include(c => c.MotorcycleModel)
                .Include(c => c.Photos)
                .Include(c => c.User)
                .ToPagedListAsync(pageNumber, pageSize);

            return View(motorcycle);

        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Motorcycles == null)
            {
                return NotFound();
            }
            var car = await _context.Motorcycles
                .Include(c => c.Photos)
                .Include(c => c.MotorcycleBrand)
                .Include(c => c.MotorcycleModel)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car != null && car.User != null)
            {
                var userId = car.User.Id;
            }
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }
        // GET: Cars/Create
        public IActionResult Create()
        {
            ViewData["MotorcycleBrandId"] = new SelectList(_context.MotorcycleBrands, "Id", "BrandName");
            ViewData["MotorcycleModelId"] = new SelectList(_context.MotorcycleModels, "Id", "ModelName");
            ViewBag.ColorOptions = new SelectList(Enum.GetValues(typeof(Color)));
            ViewBag.ConditionOptions = new SelectList(Enum.GetValues(typeof(Condition)));
            ViewBag.FuelTypeOptions = new SelectList(Enum.GetValues(typeof(FuelType)));
            ViewBag.MileageOptions = new SelectList(Enum.GetValues(typeof(Mileage)));
            ViewBag.TypeOptions = new SelectList(Enum.GetValues(typeof(MotorcycleType)));
            ViewBag.TransmissionTypeOptions = new SelectList(Enum.GetValues(typeof(TransmissionType)));
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstRegistration,EnginePower,Price,Features,Description,Location,MotorcycleBrandId,MotorcycleModelId,FuelType,Color,Condition,Mileage,MotorcycleType,TransmissionType")] Motorcycle motorcycle, List<IFormFile> photos)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            motorcycle.User = currentUser;

            if (ModelState.IsValid)
            {
                if (photos != null && photos.Count > 0)
                {
                    motorcycle.Photos = new List<MotorcyclePhoto>();

                    foreach (var photo in photos)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await photo.CopyToAsync(memoryStream);
                            motorcycle.Photos.Add(new MotorcyclePhoto
                            {
                                PhotoData = memoryStream.ToArray(),
                                ContentType = photo.ContentType
                            });
                        }
                    }
                }
                _context.Add(motorcycle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MotorcycleBrandId"] = new SelectList(_context.MotorcycleBrands, "Id", "BrandName");
            ViewData["MotorcycleModelId"] = new SelectList(_context.MotorcycleModels, "Id", "ModelName");
            ViewBag.ColorOptions = new SelectList(Enum.GetValues(typeof(Color)));
            ViewBag.ConditionOptions = new SelectList(Enum.GetValues(typeof(Condition)));
            ViewBag.FuelTypeOptions = new SelectList(Enum.GetValues(typeof(FuelType)));
            ViewBag.MileageOptions = new SelectList(Enum.GetValues(typeof(Mileage)));
            ViewBag.TypeOptions = new SelectList(Enum.GetValues(typeof(MotorcycleType)));
            ViewBag.TransmissionTypeOptions = new SelectList(Enum.GetValues(typeof(TransmissionType)));
            return View(motorcycle);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Motorcycles == null)
            {
                return NotFound();
            }

            var motorcycle = await _context.Motorcycles.FindAsync(id);
            if (motorcycle == null)
            {
                return NotFound();
            }
            ViewData["MotorcycleBrandId"] = new SelectList(_context.MotorcycleBrands, "Id", "BrandName", motorcycle.MotorcycleBrandId);
            ViewData["MotorcycleModelId"] = new SelectList(_context.MotorcycleModels, "Id", "ModelName", motorcycle.MotorcycleModelId);
            ViewBag.ColorOptions = new SelectList(Enum.GetValues(typeof(Color)));
            ViewBag.ConditionOptions = new SelectList(Enum.GetValues(typeof(Condition)));
            ViewBag.FuelTypeOptions = new SelectList(Enum.GetValues(typeof(FuelType)));
            ViewBag.MileageOptions = new SelectList(Enum.GetValues(typeof(Mileage)));
            ViewBag.TypeOptions = new SelectList(Enum.GetValues(typeof(MotorcycleType)));
            ViewBag.TransmissionTypeOptions = new SelectList(Enum.GetValues(typeof(TransmissionType)));
            return View(motorcycle);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstRegistration,EnginePower,Price,Features,Description,Location,MotorcycleBrandId,MotorcycleModelId,FuelType,Color,Condition,Mileage,MotorcycleType,TransmissionType")] Motorcycle motorcycle)
        {
            if (id != motorcycle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(motorcycle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MotorcycleExists(motorcycle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MotorcycleBrandId"] = new SelectList(_context.MotorcycleBrands, "Id", "BrandName", motorcycle.MotorcycleBrandId);
            ViewData["MotorcycleModelId"] = new SelectList(_context.MotorcycleModels, "Id", "ModelName", motorcycle.MotorcycleModelId);
            ViewBag.ColorOptions = new SelectList(Enum.GetValues(typeof(Color)));
            ViewBag.ConditionOptions = new SelectList(Enum.GetValues(typeof(Condition)));
            ViewBag.FuelTypeOptions = new SelectList(Enum.GetValues(typeof(FuelType)));
            ViewBag.MileageOptions = new SelectList(Enum.GetValues(typeof(Mileage)));
            ViewBag.TypeOptions = new SelectList(Enum.GetValues(typeof(MotorcycleType)));
            ViewBag.TransmissionTypeOptions = new SelectList(Enum.GetValues(typeof(TransmissionType)));
            return View(motorcycle);
        }
        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Motorcycles == null)
            {
                return NotFound();
            }

            var car = await _context.Motorcycles
                .Include(c => c.MotorcycleBrand)
                .Include(c => c.MotorcycleModel)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }


        // POST: Motorcycles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Motorcycles == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Motorcycles'  is null.");
            }
            var motorcycle = await _context.Motorcycles.FindAsync(id);
            if (motorcycle != null)
            {
                _context.Motorcycles.Remove(motorcycle);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool MotorcycleExists(int id)
        {
            return (_context.Motorcycles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> FilterMotorcycles(

AutoMarket/Views/Motorcycles/Create.cshtml
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#MotorcycleBrandId').change(function () {
                var brandId = $(this).val();
                if (brandId) {
                    $.ajax({
                        url: '@Url.Action("GetModelsByBrand", "Motorcycles")',
                        type: 'GET',
                        data: { brandId: brandId },
                        success: function (data) {
                            $('#MotorcycleModelId').empty();
                            $.each(data, function (i, model) {
                                $('#MotorcycleModelId').append($('<option></option>').val(model.value).text(model.text));
                            });
                        }
                    });
                } else {
                    $('#MotorcycleModelId').empty();
                }
            });
        });
    </script>
}

@model AutoMarket.Models.Motorcycle

@{
    ViewData["Title"] = "Create";
}

<h1>Create Motorcycle</h1>

<h4>Motorcycle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstRegistration" class="control-label"></label>
                <input asp-for="FirstRegistration" class="form-control" />
                <span asp-validation-for="FirstRegistration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EnginePower" class="control-label"></label>
                <input asp-for="EnginePower" class="form-control" />
                <span asp-validation-for="EnginePower" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotorcycleType"></label>
                <select asp-for="MotorcycleType" class="form-control" asp-items="ViewBag.TypeOptions">
                    <option value="">Select Type</option>
                </select>
                <span asp-validation-for="MotorcycleType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotorcycleBrandId" class="control-label"></label>
                <select id="MotorcycleBrandId" asp-for="MotorcycleBrandId" class="form-control" asp-items="ViewBag.MotorcycleBrandId">
                    <option value="">Select Motorcycle Brand</option>
                </select>
                <span asp-validation-for="MotorcycleBrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotorcycleModelId" class="control-label"></label>
                <select id="MotorcycleModelId" asp-for="MotorcycleModelId" class="form-control">
                    <option value="">Select Motorcycle Model</option>
                </select>
                <span asp-validation-for="MotorcycleModelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color"></label>
                <select asp-for="Color" class="form-control" asp-items="ViewBag.ColorOptions">
                    <option value="">Select Color</option>
                </select>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition"></label>
                <select asp-for="Condition" class="form-control" asp-items="ViewBag.ConditionOptions">
                    <option value="">Select Condition</option>
                </select>
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FuelType"></label>
                <select asp-for="FuelType" class="form-control" asp-items="ViewBag.FuelTypeOptions">
                    <option value="">Select Fuel Type</option>
                </select>
                <span asp-validation-for="FuelType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mileage"></label>
                <select asp-for="Mileage" class="form-control" asp-items="ViewBag.MileageOptions">
                    <option value="">Select Mileage</option>
                </select>
                <span asp-validation-for="Mileage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransmissionType"></label>
                <select asp-for="TransmissionType" class="form-control" asp-items="ViewBag.TransmissionTypeOptions">
                    <option value="">Select Transmission Type</option>
                </select>
                <span asp-validation-for="TransmissionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photos" class="control-label"></label>
                <input type="file" name="photos" multiple class="form-control" />
                <span asp-validation-for="Photos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AutoMarket/Views/Motorcycles/Delete.cshtml
@model AutoMarket.Models.Motorcycle

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Motorcycle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstRegistration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstRegistration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnginePower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnginePower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotorcycleBrand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotorcycleBrand.BrandName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AutoMarket/Views/Motorcycles/Details.cshtml
@model AutoMarket.Models.Motorcycle

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Motorcycle</h4>
    <hr />
    @if (Model.Photos != null && Model.Photos.Any())
    {
        <div class="row">
            @foreach (var photo in Model.Photos)
            {
                <div class="col-md-3 mb-3">
                    <img src="data:image/jpeg;base64,@Convert.ToBase64String(photo.PhotoData)" alt="Motorcycle Photo" class="img-fluid" />
                </div>
            }
        </div>
    }
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstRegistration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstRegistration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EnginePower)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EnginePower)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotorcycleBrand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotorcycleBrand.BrandName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

AutoMarket/Views/Motorcycles/FilterMotorcycles.cshtml
@model AutoMarket.ViewModel.FilterMotorcyclesViewModel

@{
    ViewData["Title"] = "Filter Motorcycles";
}

<h2 class="text-center my-4">Filter Motorcycles</h2>

<div class="container">
    @using (Html.BeginForm("FilterMotorcycles", "Motorcycles", FormMethod.Get))
    {
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Brand:</label>
                    @Html.DropDownListFor(model => model.BrandId, new SelectList(Model.Brands, "Id", "BrandName"), "Select Brand", new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Model:</label>
                    @Html.DropDownListFor(model => model.ModelId, new SelectList(Model.Models, "Id", "ModelName"), "Select Model", new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Fuel Type:</label>
                    @Html.DropDownListFor(model => model.fuelType, new SelectList(Enum.GetValues(typeof(Models.Enums.FuelType))), "Select Fuel Type", new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Color:</label>
                    @Html.DropDownListFor(model => model.color, new SelectList(Enum.GetValues(typeof(Models.Enums.Color))), "Select Color", new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Mileage:</label>
                    @Html.DropDownListFor(model => model.mileage, new SelectList(Enum.GetValues(typeof(Models.Enums.Mileage))), "Select Mileage", new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Transmission Type:</label>
                    @Html.DropDownListFor(model => model.transmissionType, new SelectList(Enum.GetValues(typeof(Models.Enums.TransmissionType))), "Select Transmission Type", new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Start Date:</label>
                    @Html.TextBoxFor(model => model.StartDate, new { type = "date", @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>End Date:</label>
                    @Html.TextBoxFor(model => model.EndDate, new { type = "date", @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Sort by Price:</label>
                    @Html.DropDownListFor(model => model.SortByPrice, new SelectList(new[]
                             {
                new { Value = "lowToHigh", Text = "Low to High" },
                new { Value = "highToLow", Text = "High to Low" }
                }, "Value", "Text"), "Select Sort Order", new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Condition:</label>
                    @Html.DropDownListFor(model => model.condition, new SelectList(Enum.GetValues(typeof(Models.Enums.Condition))), "Select Condition", new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>Price Range:</label>
                    <div class="form-row">
                        <div class="col">
                            @Html.TextBoxFor(model => model.MinPrice, new { placeholder = "Min Price", @class = "form-control" })
                        </div>
                        <div class="col">
                            @Html.TextBoxFor(model => model.MaxPrice, new { placeholder = "Max Price", @class = "form-control" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>Motorcycle Type:</label>
                    @Html.DropDownListFor(model => model.type, new SelectList(Enum.GetValues(typeof(Models.Enums.MotorcycleType))), "Select Motorcycle Type", new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-primary">Filter</button>
        </div>
    }
</div>

@if (Model.FilteredMotorcycles != null && Model.FilteredMotorcycles.Any())
{
    <h3 class="text-center my-4">Filtered Motorcycles</h3>
    <div class="container">
        <div class="row">
            @foreach (var motorcycle in Model.FilteredMotorcycles)
            {
                <a href="@Url.Action("Details", "Motorcycles", new { id = motorcycle.Id })" class="col-md-4" style="text-decoration: none; color: inherit;">
                    <div class="card mb-4 shadow-sm" style="border: 1px solid #dee2e6; border-radius: 0.25rem; cursor: pointer;">
                        @if (motorcycle.Photos != null && motorcycle.Photos.Any())
                        {
                            <img src="data:@(motorcycle.Photos.First().ContentType);base64,@(Convert.ToBase64String(motorcycle.Photos.First().PhotoData))" alt="Motorcycle Photo" style="height: 200px; object-fit: cover; border-top-left-radius: 0.25rem; border-top-right-radius: 0.25rem;">
                        }
                        else
                        {
                            <img src="path/to/default/image.jpg" alt="No Photo" style="height: 200px; object-fit: cover; border-top-left-radius: 0.25rem; border-top-right-radius: 0.25rem;">
                        }
                        <div class="card-body" style="padding: 1rem;">
                            <h5 class="card-title" style="font-size: 1.25rem; margin-bottom: 0.75rem;">@motorcycle.MotorcycleBrand.BrandName @motorcycle.MotorcycleModel.ModelName</h5>
                            <p class="card-text" style="font-size: 0.875rem;">
                                <strong>Date:</strong> @motorcycle.FirstRegistration.ToShortDateString()<br>
                                <strong>Fuel Type:</strong> @motorcycle.FuelType<br>
                                <strong>Color:</strong> @motorcycle.Color<br>
                                <strong>Transmission:</strong> @motorcycle.TransmissionType<br>
                                <h4><strong>Price:</strong> @motorcycle.Price $</h4>
                            </p>
                        </div>
                    </div>
                </a>
            }
        </div>
    </div>
}